version: '3'

services:

  web_api:
    container_name: python
    build:
      context: ./web_api
      dockerfile: Dockerfile.dev
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web_api:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:10
    environment:
      POSTGRES_DB: symphony_db
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
