FROM python:3.6

RUN groupadd --gid "1001" user \
 && useradd --uid "1001" --gid "1001" --create-home --shell /bin/bash user

ENV HOME_DIR=/home/user
ENV APP_DIR=$HOME_DIR/app
ENV PYTHONUSERBASE=$HOME_DIR/.pyvenv
ENV PATH $PYTHONUSERBASE/bin:$PATH

RUN mkdir -p $APP_DIR
COPY ./src  $APP_DIR
COPY requirements.txt $APP_DIR
RUN chown -Rv user $APP_DIR

USER user
WORKDIR $APP_DIR

RUN pip install --user --no-cache-dir -r requirements.txt
