# Generated by Django 2.0.6 on 2018-06-03 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'new'), (2, 'in progress'), (3, 'shipped'), (4, 'completed'), (5, 'cancelled')], db_index=True, default=1, verbose_name='status')),
                ('shipping_details', models.TextField(blank=True, verbose_name='shipping details')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('shipment_date', models.DateTimeField(blank=True, null=True, verbose_name='shipment date')),
                ('close_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='close date')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Sum of all the products prices and their quantities.', max_digits=10, null=True, verbose_name='sum of all the products prices')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderProductMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderProductMembership', to='products.Product', verbose_name='products'),
        ),
    ]
