# Generated by Django 2.0.6 on 2018-06-03 20:19
from django.core.management import call_command
from django.db import migrations


def loadfixtures(apps, schema_editor):
    call_command('loaddata', 'initial_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loadfixtures, reverse_code=migrations.RunPython.noop)
    ]
